name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Running hello
        uses: actions/checkout@v1
      - run: echo Hello World
      - name: Running Linux version
        run: |
          echo Running on Linux
          uname -a
